"""
VULNIX - Jira Integration Module
Export vulnerability findings to Jira tickets
"""

import json
import os
from typing import Dict, List, Optional, Any
from datetime import datetime
from pathlib import Path


class JiraExporter:
    """Export vulnerabilities to Jira issues."""

    ISSUE_TYPES = {
        "critical": "Bug",
        "high": "Bug",
        "medium": "Task",
        "low": "Task",
        "info": "Task",
    }

    PRIORITIES = {
        "critical": "Highest",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Lowest",
    }

    SEVERITY_LABELS = {
        "critical": ["security", "vulnerability", "critical"],
        "high": ["security", "vulnerability"],
        "medium": ["security", "technical-debt"],
        "low": ["security", "low-priority"],
        "info": ["informational"],
    }

    def __init__(
        self,
        jira_url: Optional[str] = None,
        project_key: Optional[str] = None,
        username: Optional[str] = None,
        api_token: Optional[str] = None,
    ):
        self.jira_url = jira_url or os.getenv("JIRA_URL")
        self.project_key = project_key or os.getenv("JIRA_PROJECT_KEY")
        self.username = username or os.getenv("JIRA_USERNAME")
        self.api_token = api_token or os.getenv("JIRA_API_TOKEN")
        self.export_file = "jira_export.json"

    def authenticate(self) -> bool:
        """Test Jira authentication."""
        if not all([self.jira_url, self.username, self.api_token]):
            return False

        try:
            import httpx
            response = httpx.get(
                f"{self.jira_url}/rest/api/3/myself",
                auth=(self.username, self.api_token),
                timeout=10,
            )
            return response.status_code == 200
        except Exception:
            return False

    def create_ticket(self, finding: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Create a single Jira ticket from a finding."""
        if not self.project_key:
            return None

        summary = f"[{finding.get('severity', 'info').upper()}] {finding.get('type', 'Vulnerability')} - {finding.get('url', 'Unknown URL')}"

        description = self._build_description(finding)

        issue_data = {
            "fields": {
                "project": {"key": self.project_key},
                "summary": summary,
                "description": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                        {
                            "type": "paragraph",
                            "content": [
                                {"type": "text", "text": description}
                            ]
                        }
                    ]
                },
                "issuetype": {"name": self.ISSUE_TYPES.get(finding.get("severity", "medium"), "Task")},
                "priority": {"name": self.PRIORITIES.get(finding.get("severity", "medium"), "Medium")},
                "labels": self.SEVERITY_LABELS.get(finding.get("severity", "info"), []),
            }
        }

        if self.jira_url and self.username and self.api_token:
            return self._submit_to_jira(issue_data)

        return self._save_to_file(issue_data, finding)

    def _build_description(self, finding: Dict[str, Any]) -> str:
        """Build Jira issue description."""
        lines = []

        lines.append(f"*Severity:* {finding.get('severity', 'unknown').upper()}")
        lines.append(f"*URL:* {finding.get('url', 'N/A')}")
        lines.append("")

        if "description" in finding:
            lines.append(f"*Description:*\n{finding['description']}")
            lines.append("")

        if "remediation" in finding:
            lines.append(f"*Remediation:*\n{finding['remediation']}")
            lines.append("")

        if "cvss" in finding and isinstance(finding["cvss"], dict):
            cvss = finding["cvss"]
            lines.append(f"*CVSS Score:* {cvss.get('score', 'N/A')}")
            if "vector" in cvss:
                lines.append(f"*CVSS Vector:* {cvss['vector']}")
            lines.append("")

        if "poc" in finding:
            lines.append(f"*Proof of Concept:*\n{finding['poc']}")
            lines.append("")

        lines.append("---")
        lines.append(f"_Generated by VULNIX on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")

        return "\n".join(lines)

    def _submit_to_jira(self, issue_data: Dict[str, Any]) -> Dict[str, Any]:
        """Submit issue directly to Jira."""
        try:
            import httpx

            response = httpx.post(
                f"{self.jira_url}/rest/api/3/issue",
                json=issue_data,
                auth=(self.username, self.api_token),
                headers={"Content-Type": "application/json"},
                timeout=30,
            )

            if response.status_code in [200, 201]:
                return {
                    "success": True,
                    "ticket_key": response.json().get("key"),
                    "ticket_url": f"{self.jira_url}/browse/{response.json().get('key')}",
                }
            else:
                return {
                    "success": False,
                    "error": f"Jira API error: {response.status_code}",
                    "response": response.text,
                }

        except Exception as e:
            return {
                "success": False,
                "error": str(e),
            }

    def _save_to_file(
        self,
        issue_data: Dict[str, Any],
        finding: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Save ticket to file for later import."""
        exports = []

        if Path(self.export_file).exists():
            with open(self.export_file, "r", encoding="utf-8") as f:
                exports = json.load(f)

        ticket_id = f"VULN-{len(exports) + 1:04d}"

        export_record = {
            "ticket_id": ticket_id,
            "finding": finding,
            "issue_data": issue_data,
            "created_at": datetime.now().isoformat(),
        }

        exports.append(export_record)

        with open(self.export_file, "w", encoding="utf-8") as f:
            json.dump(exports, f, indent=2, ensure_ascii=False)

        return {
            "success": True,
            "ticket_key": ticket_id,
            "ticket_url": None,
            "exported_to_file": True,
            "message": f"Ticket saved to {self.export_file}",
        }

    def export_findings(
        self,
        findings: List[Dict[str, Any]],
        create_epic: bool = False,
        epic_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Export multiple findings as Jira tickets."""
        results = {
            "total": len(findings),
            "created": [],
            "failed": [],
            "skipped": 0,
        }

        if create_epic and self.project_key and self.jira_url:
            epic_key = self._create_epic(epic_name or "Vulnerability Assessment")
            results["epic_key"] = epic_key

        for finding in findings:
            result = self.create_ticket(finding)

            if result and result.get("success"):
                results["created"].append({
                    "ticket_key": result["ticket_key"],
                    "url": result.get("ticket_url"),
                    "finding_type": finding.get("type"),
                })

                if create_epic and self.jira_url:
                    self._add_to_epic(result["ticket_key"], results.get("epic_key", ""))
            else:
                results["failed"].append({
                    "finding": finding.get("type"),
                    "error": result.get("error") if result else "Unknown error",
                })

        return results

    def _create_epic(self, name: str) -> Optional[str]:
        """Create an epic for the vulnerability assessment."""
        if not all([self.jira_url, self.username, self.api_token, self.project_key]):
            return None

        try:
            import httpx

            epic_data = {
                "fields": {
                    "project": {"key": self.project_key},
                    "summary": f"Epic: {name}",
                    "description": {
                        "type": "doc",
                        "version": 1,
                        "content": [
                            {
                                "type": "paragraph",
                                "content": [
                                    {
                                        "type": "text",
                                        "text": f"Vulnerability assessment created by VULNIX on {datetime.now().strftime('%Y-%m-%d')}"
                                    }
                                ]
                            }
                        ]
                    },
                    "issuetype": {"name": "Epic"},
                }
            }

            response = httpx.post(
                f"{self.jira_url}/rest/api/3/issue",
                json=epic_data,
                auth=(self.username, self.api_token),
                headers={"Content-Type": "application/json"},
                timeout=30,
            )

            if response.status_code in [200, 201]:
                return response.json().get("key")

        except Exception:
            pass

        return None

    def _add_to_epic(self, issue_key: str, epic_key: str) -> bool:
        """Add an issue to an epic."""
        if not all([self.jira_url, self.username, self.api_token]) or not epic_key:
            return False

        try:
            import httpx

            response = httpx.post(
                f"{self.jira_url}/rest/api/3/issue/{issue_key}",
                json={
                    "fields": {
                        "parent": {"key": epic_key}
                    }
                },
                auth=(self.username, self.api_token),
                headers={"Content-Type": "application/json"},
                timeout=30,
            )

            return response.status_code in [200, 201]

        except Exception:
            return False

    def import_from_file(self) -> List[Dict[str, Any]]:
        """Import saved tickets for manual processing."""
        if not Path(self.export_file).exists():
            return []

        with open(self.export_file, "r", encoding="utf-8") as f:
            return json.load(f)

    def get_export_summary(self) -> Dict[str, Any]:
        """Get summary of exported tickets."""
        if not Path(self.export_file).exists():
            return {"total": 0, "findings": []}

        with open(self.export_file, "r", encoding="utf-8") as f:
            exports = json.load(f)

        severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}

        for export in exports:
            sev = export.get("finding", {}).get("severity", "info").lower()
            if sev in severity_counts:
                severity_counts[sev] += 1

        return {
            "total": len(exports),
            "by_severity": severity_counts,
            "file": self.export_file,
        }


class JiraImportExport:
    """Import/Export utilities for Jira integration."""

    @staticmethod
    def generate_csv(findings: List[Dict[str, Any]], output_file: str = "vulnix_findings.csv") -> str:
        """Export findings to CSV for manual Jira import."""
        import csv

        with open(output_file, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)

            writer.writerow([
                "Summary",
                "Severity",
                "Type",
                "URL",
                "Description",
                "Remediation",
                "CVSS Score",
                "CVSS Vector",
            ])

            for finding in findings:
                writer.writerow([
                    f"[{finding.get('severity', '').upper()}] {finding.get('type', '')}",
                    finding.get("severity", ""),
                    finding.get("type", ""),
                    finding.get("url", ""),
                    finding.get("description", ""),
                    finding.get("remediation", ""),
                    finding.get("cvss", {}).get("score", "") if isinstance(finding.get("cvss"), dict) else "",
                    finding.get("cvss", {}).get("vector", "") if isinstance(finding.get("cvss"), dict) else "",
                ])

        return output_file

    @staticmethod
    def generate_jira_csv(findings: List[Dict[str, Any]], output_file: str = "jira_import.csv") -> str:
        """Generate CSV in Jira import format."""
        import csv

        with open(output_file, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)

            writer.writerow([
                "Project",
                "Issue Type",
                "Summary",
                "Description",
                "Priority",
                "Labels",
                "URL",
            ])

            for finding in findings:
                severity = finding.get("severity", "medium").lower()
                issue_type = JiraExporter.ISSUE_TYPES.get(severity, "Task")

                description = f"*Severity:* {severity.upper()}\n"
                description += f"*URL:* {finding.get('url', 'N/A')}\n\n"
                description += f"*Description:* {finding.get('description', '')}\n\n"
                description += f"*Remediation:* {finding.get('remediation', '')}"

                writer.writerow([
                    "PROJECT",
                    issue_type,
                    f"[{severity.upper()}] {finding.get('type', 'Vulnerability')} - {finding.get('url', '')}",
                    description,
                    JiraExporter.PRIORITIES.get(severity, "Medium"),
                    ",".join(JiraExporter.SEVERITY_LABELS.get(severity, [])),
                    finding.get("url", ""),
                ])

        return output_file